services:
  web:
    build: .
    image: el-proprete:latest
    container_name: el-proprete
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - default
      - proxy-network

networks:
  proxy-network:
    external: true
